### ISSUE TITLE
use `http-server` to serve webpages?

### ISSUE THREAD

**Issue by tcr** [jquery/2015-developer-summit#13]
Would it be helpful for me to PR a `index.js` that launches a static web server?

Opening the `index.html` from my filesystem had weird CSS errors. (I might have done it wrong.)

**Comment by ashleygwilliams** [comment]
i'm not sure that the added complexity is worth it. did you file an issue for the bug? ;)

**Comment by tcr** [comment]
I haven't! Though now it would go like:

Steps to reproduce
1. Hit refresh, Tim
2. It works now

Can mark as resolved.

**Comment by ashleygwilliams** [comment]
:) i think given that we don't have a bug to fix, we'll keep it simple for now. closing. might reconsider as we get more complicated (build steps, auto refresh, etc)
